Avoid errors during validation when missing time dimensions (#467)
Resolves [JIRA](https://dbtlabs.atlassian.net/jira/software/c/projects/DI/boards/1602?selectedIssue=DI-3283)

<!---
  Include the number of the issue addressed by this PR above if applicable.
  PRs for code changes without an associated issue *will not be merged*.
  See CONTRIBUTING.md for more information.
-->

### Description

We had some users on Fusion run into strange problems because Fusion didn't enforce some of the same validations enforced in dbt-core.  See inline PR comments as pointers to the expected behaviors for our parsers (dbt-core or fusion, for instance).

The error we saw seems to be inflicted by the call to min() when we have no granularities.  The error is as follows:
```
error: dbt1005: An error occurred while running model validation to ensure that time spines are valid - ValueError: min() iterable argument is empty
```

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)